### ISSUE TITLE
Code in Office-31 and ImageCLEF?

### ISSUE THREAD

**Issue by Rigel-1994** [Mid-Push/Moving-Semantic-Transfer-Network#1]
Can you release the code about the Office-31 and ImageCLEF datasets? I find it really tricky and hard to make it work in both datasets.

**Comment by Mid-Push** [comment]
Hi, The code for Office will be available in the next few days. 
 For your own implementation, several tips are offered:
1. Source images random crop to 256 while Target images center crop (following JAN and DANN )
2. Image Random flipping (JAN and DANN)
3, Domain adversarial loss is scaled by 0.1 (G_loss=0.1*G_loss, D_loss=0.1*D_loss) following DANN.

**Comment by Rigel-1994** [comment]
Is it OK now?

**Comment by Mid-Push** [comment]
Hi, the code for office-31 is available now. We also have provided a trained model for your convenience. The preprocessing step is explained at the first page in this project.
