### ISSUE TITLE
Tensorflow and python version

### ISSUE THREAD

**Issue by abcdvzz** [Mid-Push/Moving-Semantic-Transfer-Network#2]
Could you please tell me the tensorflow and python version of your code? Something got wrong when I implemented your work, and I'd like to figure out if it is caused by different versions. Thank you very much.

**Comment by Mid-Push** [comment]
Hi,
tensorflow_gpu==1.4.0
python2.7

Iguess u need following advices:
For digit tasks,you had better check the parameter initialization and hyper-parameters.
For office task, preprocessing also plays a significant role in the performance.

**Comment by abcdvzz** [comment]
Thank you very much. And I'd like to know if it's convenient for you to make your slides public or where can I get it.

**Comment by Mid-Push** [comment]
Sorry for the late reply. The slides are available at 

http://shaoan.vision/publications/icml2018_slides.pdf
