### ISSUE TITLE
ImageClef Dataset

### ISSUE THREAD

**Issue by vinodkkurmi** [Mid-Push/Moving-Semantic-Transfer-Network#6]
@Mid-Push  Hi could you please share the information related to ImgeCLEF dataset? From where you got all the images and how did you choose image for the your task?

**Comment by Mid-Push** [comment]
Hi,
The ImageCLEF dataset is used by Joint adaptation network (icml17),  I just used their shared dataset.  https://github.com/thuml/Xlearn/tree/master/caffe

ImageCLEF has similar format as Office31. You can just follow the instructions for Office31 to do with ImageCLEF.
